version: "3"
services:
  react-app:
    image: ripunjay25/spe_final:latest
    stdin_open: true
    ports:
        - "3000:3000"
    networks:
      - mern-app      
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.23-xenial
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
